### ISSUE TITLE
CV Player

### ISSUE THREAD

**Issue by SmallLuma** [Strrationalism/Yukimi#3]
角色配音播放器。

单例对象，提供单个轨道的角色配音播放功能。

公开成员函数
+ Play(AssetName ass)    重置所有状态，淡出停止之前播放的声音，异步加载ass，并在淡出停止后，播放ass
+ FadeOut()    使用0.25秒淡出并停止角色配音
+ VolumeDown()    使用0.25秒时间，声音渐变到0.5
+ VolumeUp()    使用0.25秒时间，声音渐变到1.0，与VolumeDown搭配使用

**Comment by Rabenda** [comment]
VolumeUp(float time) 使用0.5秒时间，声音渐变到1.0，与VolumeDown搭配使用

参数删除 修改成VolumeUp()

**Comment by SmallLuma** [comment]
#15
