### ISSUE TITLE
脚本设计大纲

### ISSUE THREAD

**Issue by astronomicalphenomena** [Strrationalism/Yukimi#5]
基本词素：
`【人名】:【对话】`：说话
` (特效) `：显示某个特效
`【人名】:(特效)【对话】`：显示具特定特效的话
````
select 【N】 【选项】 
or【选项】
or【选项】
````
：第N个选择，令选择某个选项
`label 【名称】`：用于跳转的标签
`if N select M goto 【名称】`：如果第N个选择支选择了第M个选项，则跳转到label 【名称】位置
`end 【N】`：第N个结局

**Comment by SmallLuma** [comment]
缺少演出指令的语法。

可以考虑推pr。

**Comment by SmallLuma** [comment]
转到此处：https://github.com/Strrationalism/Yukimi/blob/YukimiScriptDesign/YukimiScriptDesign.md
